#!/usr/bin/env bash

./main.py First message.
./main.py Second message..
./main.py Third message...
./main.py Fourth message....
./main.py Fifth message.....
./main.py Sixth message......
./main.py Seventh message.......
./main.py Eigth message........
